---
- hosts: test
  tasks:
  - name: Ensure permissions on /etc/crontab are configured
    file:
       path: /etc/crontab
       owner: root
       group: root
       mode: '0600'
  - name: Ensure permissions on /etc/cron.hourly are configured
    file:
       path: /etc/cron.hourly
       owner: root
       group: root
       mode: '0700'
  - name: Ensure permissions on /etc/cron.daily are configured
    file:
       path: /etc/cron.daily
       owner: root
       group: root
       mode: '0700'
  - name: Ensure permissions on /etc/cron.weekly are configured
    file:
       path: /etc/cron.weekly
       owner: root
       group: root
       mode: '0700'
  - name: Ensure permissions on /etc/cron.monthly are configured
    file:
       path: /etc/cron.monthly
       owner: root
       group: root
       mode: '0700'
  - name: Ensure permissions on /etc/cron.d are configured
    file:
       path: /etc/cron.d
       owner: root
       group: root
       mode: '0700'
  - name: Ensure at/cron is restricted to authorized users
    file:
       path: /etc/cron.deny
       owner: root
       group: root
       mode: '0600'
    ignore_errors: yes



  - name: check /etc/cron.allow exists
    stat:
     path: /etc/cron.allow
    register: cron_allow

  - name: /etc/cron.allow permissions
    file:
     path: /etc/cron.allow
     mode: 0600
     owner: root
     group: root
     state: touch
    when: not cron_allow.stat.exists

  - name: /etc/cron.allow permissions
    file:
     path: /etc/cron.allow
     mode: 0600
     owner: root
     group: root
    when: cron_allow.stat.exists


  - name: check /etc/at.allow exists
    stat:
     path: /etc/at.allow
    register: at_allow

  - name: /etc/at.allow permissions
    file:
     path: /etc/at.allow
     mode: 0600
     owner: root
     group: root
     state: touch
    when: not at_allow.stat.exists

  - name: /etc/at.allow permissions
    file:
     path: /etc/at.allow
     mode: 0600
     owner: root
     group: root
    when: at_allow.stat.exists



  - name: check /etc/cron.deny exists
    shell: stat /etc/cron.deny
    ignore_errors: yes
    register: f_exists

  - name: copy /etc/cron.deny
    copy:
     src: /etc/cron.deny
     remote_src: yes
     dest: /usr/share/cis
     force: no
    ignore_errors: yes

  - name: remove /etc/cron.deny
    file:
     path: /etc/cron.deny
     state: absent
    when: f_exists.stdout !=  ''


  - name: check /etc/at.deny exists
    shell: stat /etc/at.deny
    ignore_errors: yes
    register: at_deny

  - name: copy /etc/at.deny
    copy:
     src: /etc/at.deny
     remote_src: yes
     dest: /usr/share/cis
     force: no
    ignore_errors: yes

  - name: remove /etc/at.deny
    file:
     path: /etc/at.deny
     state: absent
    when: at_deny.stdout !=  ''

  - name: File system integrity, root crontab
    shell: crontab -u root -l | grep aide
    register: crontab_out
    ignore_errors: yes

  - debug:
     var: crontab_out

  - name: set crontab for aide
    cron:
     name: "aide crontab"
     minute: 0
     hour: 5
     job: /usr/sbin/aide --check
    when: crontab_out.stdout == ''

