---
- hosts: test
  name: Starting Roll-Back
  tasks:
  ##############################################
  ##Rollbacking /etc/fstab
  ###############################################
  - name: roll-back fstab
    shell: ls /usr/share/cis/fstab
    register: fstab_check
    ignore_errors: yes
  - copy:
     src: /usr/share/cis/fstab
     dest: /etc
     remote_src: yes
    when: fstab_check.stdout != ""
                                         
