---
- name: Module rollback 
  hosts: test
  tasks:
  
  - name: backup
    copy:
     src: /etc/modprobe.d/CIS.conf
     dest: /usr/share/cis
     remote_src: yes

  - name: squashfs check
    shell: grep 'squashfs' /etc/modprobe.d/CIS.conf 
    register: check1
    ignore_errors: yes

  - name: Rollback squashfs
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'squashfs'
     line: ""
     insertafter: yes
     state: present
    when: check1.stdout != ""

  - name: load squashfs
    shell: modprobe squashfs
    when: check1.stdout != ""
    ignore_errors: yes

  - name: isofs check
    shell: grep 'isofs' /etc/modprobe.d/CIS.conf
    register: check2
    ignore_errors: yes

  - name: Rollback isofs
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'isofs'
     line: ""
     insertafter: yes
     state: present
    when: check2.stdout != ""

  - name: load isofs
    shell: modprobe isofs
    when: check2.stdout != ""
    ignore_errors: yes

  - name: udf check
    shell: grep 'udf' /etc/modprobe.d/CIS.conf
    register: check3
    ignore_errors: yes

  - name: Rollback udf
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'udf'
     line: ""
     insertafter: yes
     state: present
    when: check3.stdout != ""

  - name: load udf
    shell: modprobe udf
    when: check3.stdout != ""
    ignore_errors: yes

  - name: vfat check
    shell: grep 'vfat' /etc/modprobe.d/CIS.conf
    register: check4
    ignore_errors: yes

  - name: Rollback vfat
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'vfat'
     line: ""
     insertafter: yes
     state: present
    when: check4.stdout != ""

  - name: load vfat
    shell: modprobe vfat
    when: check4.stdout != ""
    ignore_errors: yes
  
  - name: dccp check
    shell: grep 'dccp' /etc/modprobe.d/CIS.conf
    register: check5
    ignore_errors: yes

  - name: Rollback dccp
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'dccp'
     line: ""
     insertafter: yes
     state: present
    when: check5.stdout != ""

  - name: load dccp
    shell: modprobe dccp
    when: check5.stdout != ""
    ignore_errors: yes
  
  - name: rds check
    shell: grep 'rds' /etc/modprobe.d/CIS.conf
    register: check6
    ignore_errors: yes

  - name: Rollback rds
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'rds'
     line: ""
     insertafter: yes
     state: present
    when: check6.stdout != ""

  - name: load rds
    shell: modprobe rds
    when: check6.stdout != ""
    ignore_errors: yes
  
  - name: sctp check
    shell: grep 'sctp' /etc/modprobe.d/CIS.conf
    register: check7
    ignore_errors: yes

  - name: Rollback sctp
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'sctp'
     line: ""
     insertafter: yes
     state: present
    when: check7.stdout != ""

  - name: load sctp
    shell: modprobe sctp
    when: check7.stdout != ""
    ignore_errors: yes

  - name: tipc check
    shell: grep 'tipc' /etc/modprobe.d/CIS.conf
    register: check8
    ignore_errors: yes

  - name: Rollback tipc
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'tipc'
     line: ""
     insertafter: yes
     state: present
    when: check8.stdout != ""

  - name: load tipc
    shell: modprobe tipc
    when: check8.stdout != ""
    ignore_errors: yes

  - name: cramfs check
    shell: grep 'cramfs' /etc/modprobe.d/CIS.conf
    register: check9
    ignore_errors: yes

  - name: Rollback cramfs
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'cramfs'
     line: ""
     insertafter: yes
     state: present
    when: check9.stdout != ""

  - name: load cramfs
    shell: modprobe cramfs
    when: check9.stdout != ""
    ignore_errors: yes

  - name: freevxfs check
    shell: grep 'freevxfs' /etc/modprobe.d/CIS.conf
    register: check10
    ignore_errors: yes

  - name: Rollback freevxfs
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'freevxfs'
     line: ""
     insertafter: yes
     state: present
    when: check10.stdout != ""

  - name: load freevxfs
    shell: modprobe freevxfs
    when: check10.stdout != ""
    ignore_errors: yes

  - name: jffs2 check
    shell: grep 'jffs2' /etc/modprobe.d/CIS.conf
    register: check11
    ignore_errors: yes

  - name: Rollback jffs2
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'jffs2'
     line: ""
     insertafter: yes
     state: present
    when: check11.stdout != ""

  - name: load jffs2
    shell: modprobe jffs2
    when: check11.stdout != ""
    ignore_errors: yes
  
  - name: hfsplus check
    shell: grep 'install hfsplus' /etc/modprobe.d/CIS.conf
    register: check13
    ignore_errors: yes

  - name: Rollback hfsplus
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'hfsplus'
     line: ""
     insertafter: yes
     state: present
    when: check13.stdout != ""

  - name: load hfsplus
    shell: modprobe hfsplus
    when: check13.stdout != ""
    ignore_errors: yes


  - name: hfs check
    shell: grep 'hfs' /etc/modprobe.d/CIS.conf
    register: check12
    ignore_errors: yes

  - name: Rollback hfs
    lineinfile:
     path: /etc/modprobe.d/CIS.conf
     regexp: 'install hfs'
     line: ""
     insertafter: yes
     state: present
    when: check12.stdout != ""

  - name: load hfs
    shell: modprobe hfs
    when: check12.stdout != ""
    ignore_errors: yes


