---
- hosts: test
  tasks:

  - name: copy sysctl.conf
    copy:
     src: /etc/sysctl.conf
     dest: /usr/share/cis/sysctl.conf
     remote_src: yes
     force: no
  
 
  - name: Ensure IP forwarding is disbaled
    sysctl:
       name: net.ipv4.ip_forward
       value: '0'
       sysctl_set: yes
       reload: yes


  - name: Ensure packet redirect sending is disabled
    sysctl:
       name: net.ipv4.conf.all.send_redirects
       value: '0'
  - sysctl:
       name: net.ipv4.conf.default.send_redirects
       value: '0'
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.conf.all.send_redirects
       value: '0'
       sysctl_set: yes
    notify: 
     - setting net ipv4 flush param
  - sysctl:
       name: net.ipv4.conf.default.send_redirects
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - name: Ensure source routed packets are not accepted
    sysctl:
       name: net.ipv4.conf.all.accept_source_route
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
       name: net.ipv4.conf.default.accept_source_route
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.conf.all.accept_redirects
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
       name: net.ipv4.conf.default.accept_redirects
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
       name: net.ipv4.conf.all.secure_redirects
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
       name: net.ipv4.conf.default.secure_redirects
       value: '0'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param



  - sysctl:
       name: net.ipv4.conf.all.log_martians
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.conf.default.log_martians
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.icmp_echo_ignore_broadcasts
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.icmp_ignore_bogus_error_responses
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.conf.all.rp_filter
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param

  - sysctl:
       name: net.ipv4.conf.default.rp_filter
       value: '1'
       sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
     name: net.ipv4.tcp_syncookies
     value: '1'
     sysctl_set: yes
    notify:
     - setting net ipv4 flush param


  - sysctl:
     name: net.ipv6.conf.all.accept_ra
     value: '0'
     sysctl_set: yes
     ignoreerrors: yes

  - sysctl:
     name: net.ipv6.conf.default.accept_ra
     value: '0'
     sysctl_set: yes
     ignoreerrors: yes

  - sysctl:
     name: net.ipv6.conf.all.accept_redirects
     value: '0'
     sysctl_set: yes
     ignoreerrors: yes


  - sysctl:
     name: net.ipv6.conf.default.accept_redirects
     value: '0'
     sysctl_set: yes
     ignoreerrors: yes
                            
  - name: Ensure ipv6 is disabled, no ipv6 entry
    shell: grep '^\s*kernel.*ipv6.disable=1.*' /boot/grub/grub.conf
    ignore_errors: yes
    register: ipv6_status


  - name: ensure /etc/hosts.allow existence
    copy:
      src: /etc/hosts.allow
      dest: /usr/share/cis
  - file:
      path: /etc/hosts.allow
      owner: root
      group: root
      mode: '644'

  - name: ensure /etc/hosts.deny existence
    copy:
      src: /etc/hosts.deny
      dest: /usr/share/cis
  - file:
     path: /etc/hosts.deny
     owner: root
     group: root
     mode: '644'

  - name: Enure /etc/hosts.deny is configured
    lineinfile:
     path: /etc/hosts.deny
     line: "ALL: ALL"
     state: present

  
  - name: disabling ipv6
    lineinfile:
     path: /boot/grub/grub.conf
     backrefs: yes
     regexp: '^(\s*kernel.*)'
     line: '\1 ipv6.disable=1'
    when: ipv6_status.stdout == ""

  - name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled
    shell: grep '^\s*kernel.*audit=1.*' /boot/grub/grub.conf
    ignore_errors: yes
    register: prior_status

  - name: adding audit=1
    lineinfile: 
     path: /boot/grub/grub.conf
     backup: True
     backrefs: True
     state: present
     regexp: '^(\s*kernel.*)'
     line: '\1 audit=1'
    when: prior_status.stdout == ""

  - name: copy /etc/securetty
    copy:
     src: /etc/securetty
     dest: /usr/share/cis/securetty
     remote_src: yes
     force: no

  - name: remove root access from securetty
    shell: echo "" > /etc/securetty

  handlers:
  - name: sleep
    pause:
     seconds: 7

  - name: setting net ipv4 flush param
    sysctl:
      name: net.ipv4.route.flush
      value: "1"
      sysctl_set: yes
      ignoreerrors: yes 
  - name: setting net ipv6 flush param
    sysctl:
      name: net.ipv6.route.flush
      value: "1"
      sysctl_set: yes
      ignoreerrors: yes

  - name: reload the rsyslogd configuration
    shell: pkill -HUP rsyslogd

  - name: reload the syslog-ng configuration
    shell: pkill -HUP syslog-ng


