---
- hosts: test
  name: This is for Roll-backing configuring-SSH PlayBook
  tasks:
  - name: set required perms on /etc/ssh/sshd_config
    copy: 
      src: /usr/share/cis/sshd_config
      dest: /etc/ssh/sshd_config
      remote_src: yes

  - name: Configure PAM
    copy: 
     src: /usr/share/cis/password-auth
     dest: /etc/pam.d/password-auth
     remote_src: yes
  
  
  - copy:
     src: /usr/share/cis/pwquality.conf
     dest: /etc/security/pwquality.conf
     remote_src: yes

#######################
#PASSWORD CONFIGURATION
#######################
  - name: roll-back system-auth file
    copy:
      src: /usr/share/cis/system-auth
      dest: /etc/pam.d/system-auth
      remote_src: yes

  - name: Roll-Back Shadow Password Suite Parameters
    copy:
      src: /usr/share/cis/login.defs
      dest: /etc/login.defs
      remote_src: yes
  
  - name: roll-back /etc/passwd
    copy:
      src: /usr/share/cis/passwd
      dest: /etc/passwd
      remote_src: yes

  - name: Roll-back /etc/bashrc
    copy: 
      src: /usr/share/cis/bashrc
      dest: /etc/bashrc
      remote_src: yes

  - name: Roll-Back /etc/profile 
    copy:
      src: /usr/share/cis/profile
      dest: /etc/profile
      remote_src: yes

  - name: Roll-Back /etc/pam.d/su
    copy:
      src: /usr/share/cis/su
      dest: /etc/pam.d/su
      remote_src: yes
  
